"""Initial migration

Revision ID: 63df1ba866b0
Revises: 
Create Date: 2025-05-23 02:26:04.541691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '63df1ba866b0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company')
    op.alter_column('log_analysis', 'company_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_log_analysis_id'), 'log_analysis', ['id'], unique=False)
    op.create_foreign_key(None, 'log_analysis', 'companies', ['company_id'], ['id'])
    op.alter_column('login_history', 'city',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('login_history', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('reports', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('reports', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('reports', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('reports', 'mitre_ids',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reports', 'mitre_ids',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('reports', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('reports', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('reports', 'id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('login_history', 'timestamp',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('login_history', 'city',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'log_analysis', type_='foreignkey')
    op.drop_index(op.f('ix_log_analysis_id'), table_name='log_analysis')
    op.alter_column('log_analysis', 'company_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.create_table('company',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('company_pkey')),
    sa.UniqueConstraint('name', name=op.f('company_name_key'))
    )
    # ### end Alembic commands ###
