"""Add source to log_analysis

Revision ID: 6696851de71c
Revises: 63df1ba866b0
Create Date: 2025-05-23 06:06:36.709643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6696851de71c'
down_revision: Union[str, None] = '63df1ba866b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log_analysis', sa.Column('source', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('log_analysis', 'source')
    # ### end Alembic commands ###
