"""add success column to login_history

Revision ID: a462962864b2
Revises: 6696851de71c
Create Date: 2025-05-27 04:55:48.073466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a462962864b2'
down_revision: Union[str, None] = '6696851de71c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('login_history', sa.Column('success', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('login_history', 'success')
    # ### end Alembic commands ###
